// Mock data for dashboard UI — replace with real DB queries once auth + Prisma are wired up

export const mockUser = {
  id: "user_1",
  email: "demo@devstash.io",
  name: "John Doe",
  isPro: false,
};

export const mockItemTypes = [
  { id: "type_snippet",  name: "Snippet",  icon: "Code",       color: "#3b82f6", isSystem: true  },
  { id: "type_prompt",   name: "Prompt",   icon: "Sparkles",   color: "#8b5cf6", isSystem: true  },
  { id: "type_note",     name: "Note",     icon: "StickyNote", color: "#fde047", isSystem: true  },
  { id: "type_command",  name: "Command",  icon: "Terminal",   color: "#f97316", isSystem: true  },
  { id: "type_link",     name: "Link",     icon: "Link",       color: "#10b981", isSystem: true  },
  { id: "type_file",     name: "File",     icon: "File",       color: "#6b7280", isSystem: true  },
  { id: "type_image",    name: "Image",    icon: "Image",      color: "#ec4899", isSystem: true  },
];

export const mockCollections = [
  {
    id: "col_1",
    name: "React Patterns",
    description: "Common React patterns and hooks",
    isFavorite: true,
    itemCount: 12,
    dominantTypeId: "type_snippet",
    previewTypeIds: ["type_snippet", "type_command", "type_link"],
  },
  {
    id: "col_2",
    name: "Python Snippets",
    description: "Useful Python code snippets",
    isFavorite: false,
    itemCount: 8,
    dominantTypeId: "type_snippet",
    previewTypeIds: ["type_snippet", "type_file"],
  },
  {
    id: "col_3",
    name: "Context Files",
    description: "AI context files for projects",
    isFavorite: true,
    itemCount: 5,
    dominantTypeId: "type_file",
    previewTypeIds: ["type_file"],
  },
  {
    id: "col_4",
    name: "Interview Prep",
    description: "Technical interview preparation",
    isFavorite: false,
    itemCount: 24,
    dominantTypeId: "type_snippet",
    previewTypeIds: ["type_snippet", "type_command", "type_link", "type_file"],
  },
  {
    id: "col_5",
    name: "Git Commands",
    description: "Frequently used git commands",
    isFavorite: true,
    itemCount: 15,
    dominantTypeId: "type_command",
    previewTypeIds: ["type_snippet", "type_file"],
  },
  {
    id: "col_6",
    name: "AI Prompts",
    description: "Curated AI prompts for coding",
    isFavorite: false,
    itemCount: 18,
    dominantTypeId: "type_prompt",
    previewTypeIds: ["type_prompt", "type_command"],
  },
];

export const mockItems = [
  {
    id: "item_1",
    title: "useAuth Hook",
    description: "Custom authentication hook for React applications",
    contentType: "text",
    content: `import { useSession } from "next-auth/react";\n\nexport function useAuth() {\n  const { data: session, status } = useSession();\n  return { user: session?.user, isLoading: status === "loading" };\n}`,
    language: "typescript",
    typeId: "type_snippet",
    isFavorite: true,
    isPinned: true,
    tags: ["react", "auth", "hooks"],
    createdAt: "2026-01-15T00:00:00Z",
  },
  {
    id: "item_2",
    title: "API Error Handling Pattern",
    description: "Fetch wrapper with exponential backoff retry logic",
    contentType: "text",
    content: `async function fetchWithRetry(url: string, retries = 3): Promise<Response> {\n  for (let i = 0; i < retries; i++) {\n    try {\n      return await fetch(url);\n    } catch (e) {\n      if (i === retries - 1) throw e;\n      await new Promise(r => setTimeout(r, 2 ** i * 1000));\n    }\n  }\n}`,
    language: "typescript",
    typeId: "type_snippet",
    isFavorite: true,
    isPinned: true,
    tags: ["api", "error-handling", "fetch"],
    createdAt: "2026-01-15T00:00:00Z",
  },
  {
    id: "item_3",
    title: "Git: Undo Last Commit",
    description: "Soft reset to keep changes staged",
    contentType: "text",
    content: "git reset --soft HEAD~1",
    language: "bash",
    typeId: "type_command",
    isFavorite: false,
    isPinned: false,
    tags: ["git", "reset"],
    createdAt: "2026-01-10T00:00:00Z",
  },
  {
    id: "item_4",
    title: "ChatGPT Code Review Prompt",
    description: "System prompt for thorough code review",
    contentType: "text",
    content: "You are a senior engineer. Review the following code for bugs, performance issues, and security vulnerabilities. Be concise and prioritize critical issues.",
    language: null,
    typeId: "type_prompt",
    isFavorite: false,
    isPinned: false,
    tags: ["chatgpt", "code-review"],
    createdAt: "2026-01-08T00:00:00Z",
  },
  {
    id: "item_5",
    title: "Next.js Project Notes",
    description: "Setup notes and gotchas for this project",
    contentType: "text",
    content: "## Setup\n- Use `npm run dev` to start\n- Tailwind v4 uses CSS config (no tailwind.config.js)\n- Auth via NextAuth v5",
    language: null,
    typeId: "type_note",
    isFavorite: false,
    isPinned: false,
    tags: ["nextjs", "setup"],
    createdAt: "2026-01-05T00:00:00Z",
  },
  {
    id: "item_6",
    title: "Docker Build & Run",
    description: "Quick reference for Docker build and run commands",
    contentType: "text",
    content: "docker build -t myapp .\ndocker run -p 3000:3000 myapp",
    language: "bash",
    typeId: "type_command",
    isFavorite: false,
    isPinned: false,
    tags: ["docker", "devops"],
    createdAt: "2026-02-01T00:00:00Z",
  },
  {
    id: "item_7",
    title: "Prisma Schema Notes",
    description: "Notes on Prisma schema design patterns and gotchas",
    contentType: "text",
    content: "## Key Notes\n- Use @default(cuid()) for IDs\n- Always run migrate dev (never db push)\n- Use @updatedAt for timestamps",
    language: null,
    typeId: "type_note",
    isFavorite: false,
    isPinned: false,
    tags: ["prisma", "database"],
    createdAt: "2026-02-10T00:00:00Z",
  },
  {
    id: "item_8",
    title: "CSS Grid Complete Guide",
    description: "CSS Tricks comprehensive guide to CSS Grid Layout",
    contentType: "url",
    content: null,
    language: null,
    typeId: "type_link",
    isFavorite: true,
    isPinned: false,
    tags: ["css", "grid", "reference"],
    createdAt: "2026-02-15T00:00:00Z",
  },
  {
    id: "item_9",
    title: "Code Review Prompt",
    description: "Detailed prompt for thorough AI code review sessions",
    contentType: "text",
    content: "You are a senior software engineer conducting a thorough code review. Analyze the code for bugs, performance issues, security vulnerabilities, and style inconsistencies. Prioritize critical issues.",
    language: null,
    typeId: "type_prompt",
    isFavorite: false,
    isPinned: false,
    tags: ["code-review", "ai"],
    createdAt: "2026-02-20T00:00:00Z",
  },
  {
    id: "item_10",
    title: "useDebounce Hook",
    description: "Custom hook for debouncing values in React",
    contentType: "text",
    content: `import { useState, useEffect } from "react";\n\nexport function useDebounce<T>(value: T, delay: number): T {\n  const [debouncedValue, setDebouncedValue] = useState(value);\n  useEffect(() => {\n    const timer = setTimeout(() => setDebouncedValue(value), delay);\n    return () => clearTimeout(timer);\n  }, [value, delay]);\n  return debouncedValue;\n}`,
    language: "typescript",
    typeId: "type_snippet",
    isFavorite: true,
    isPinned: false,
    tags: ["react", "hooks", "debounce"],
    createdAt: "2026-03-01T00:00:00Z",
  },
  {
    id: "item_11",
    title: "AWS S3 Sync Command",
    description: "Sync local directory to S3 bucket with exclusions",
    contentType: "text",
    content: "aws s3 sync ./dist s3://my-bucket --exclude '*.map' --delete",
    language: "bash",
    typeId: "type_command",
    isFavorite: false,
    isPinned: false,
    tags: ["aws", "s3", "deploy"],
    createdAt: "2026-03-10T00:00:00Z",
  },
  {
    id: "item_12",
    title: "Zod Form Schema",
    description: "Reusable Zod schema for common form validation patterns",
    contentType: "text",
    content: `import { z } from "zod";\n\nexport const userSchema = z.object({\n  email: z.string().email(),\n  password: z.string().min(8),\n  name: z.string().min(2).max(50),\n});`,
    language: "typescript",
    typeId: "type_snippet",
    isFavorite: false,
    isPinned: false,
    tags: ["zod", "validation", "forms"],
    createdAt: "2026-03-15T00:00:00Z",
  },
];

// Sidebar type counts (derived from items in a real app)
export const mockTypeCounts: Record<string, number> = {
  type_snippet: 24,
  type_prompt:  19,
  type_command: 15,
  type_note:    12,
  type_file:     5,
  type_image:    3,
  type_link:     8,
};

export const mockStats = {
  totalItems: Object.values(mockTypeCounts).reduce((sum, n) => sum + n, 0),
  totalCollections: mockCollections.length,
  favoriteItems: 14,
  favoriteCollections: mockCollections.filter((c) => c.isFavorite).length,
};